version: "3.7"

services:
  database:
    image: postgres:alpine3.14
    restart: always
    ports:
      - "5500:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=penpal"
      - "PGDATA=/data/postgres"
      - "POSTGRES_DB=penpal_clone"
    volumes:
      - postgres_data:/data/postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=yigitsadic@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=loremipsum"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "7575:80"
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin:
